
name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        STRATEGY_NAME: [t1, t2, t5]

    steps:
    - name: Checkout github repo
      uses: actions/checkout@v2
      with:
          lfs: true
    - name: Checkout LFS objects
      run: git lfs checkout
    - name: Install dependencies
      run: |
        sudo apt-get update -qq
        sudo apt-get install -y gcc \
                                g++ \
                                make \
                                binutils \
                                libx11-dev \
                                libxpm-dev \
                                libxft-dev \
                                libxext-dev \
                                qt5-default \
                                git \
                                cmake \
                                python3.7-dev \
                                ccache \
                                fftw3-dev
        gcc -v
        cd
    - name: Run the test in docker
      run: |
        ls $GITHUB_WORKSPACE
        docker run --rm -e "TEST=${STRATEGY_NAME}" -v $GITHUB_WORKSPACE:/home tbaudier/gatebenchmarks /home/GateBenchmarks/ci/runTest.sh
        ls $HOME/software
        ls $HOME/software/GateBenchmarks

